name       : libical
version    : 3.0.3
release    : 4
source     :
    - https://github.com/libical/libical/releases/download/v3.0.3/libical-3.0.3.tar.gz : 5b91eb8ad2d2dcada39d2f81d5e3ac15895823611dc7df91df39a35586f39241
license    : MPL-2.0
component  : desktop.library
summary    : An implementation of the iCalendar protocols and data formats
description: |
    Libical is an Open Source implementation of the iCalendar protocols and protocol data units. The iCalendar specification describes how calendar clients can communicate with calendar servers so users can store their calendar data and arrange meetings with other users.
setup      : |
    %cmake_ninja -DSHARED_ONLY=yes \
        -DLIB_SUFFIX=64
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
