name       : libical
version    : 1.0.1
release    : 2
source     :
    - https://github.com/libical/libical/releases/download/v1.0.1/libical-1.0.1.tar.gz : 089ce3c42d97fbd7a5d4b3c70adbdd82115dd306349c1f5c46a8fb3f8c949592
license    : GPL-2.0
summary    : The libical package contains an implementation of the iCalendar protocols and data formats.
description: |
    The libical package contains an implementation of the iCalendar protocols and data formats.
setup      : |
    %cmake -DSHARED_ONLY=yes -DLIB_SUFFIX=64 .
build      : |
    %make
install    : |
    %make_install
