name       : libical
version    : 3.0.6
release    : 6
source     :
    - https://github.com/libical/libical/releases/download/v3.0.6/libical-3.0.6.tar.gz : 5c8a21c2b732ece4a33e5c862970b4f35a8548bbcda50de5695f6fc211ac4d97
license    : MPL-2.0
component  : desktop.library
summary    : An implementation of the iCalendar protocols and data formats
description: |
    Libical is an Open Source implementation of the iCalendar protocols and protocol data units. The iCalendar specification describes how calendar clients can communicate with calendar servers so users can store their calendar data and arrange meetings with other users.
builddeps  :
    - db5-devel
    - vala
rundeps    :
    - devel :
        - db5-devel
setup      : |
    %cmake_ninja -DICAL_GLIB_VAPI=yes \
        -DGOBJECT_INTROSPECTION=yes \
        -DENABLE_GTK_DOC=no \
        -DLIB_SUFFIX=64 \
        -DSHARED_ONLY=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
