name       : libical
version    : 2.0.0
release    : 3
source     :
    - https://github.com/libical/libical/releases/download/v2.0.0/libical-2.0.0.tar.gz : 654c11f759c19237be39f6ad401d917e5a05f36f1736385ed958e60cf21456da
license    : GPL-2.0
component  : desktop.library
summary    : The libical package contains an implementation of the iCalendar protocols and data formats.
description: |
    The libical package contains an implementation of the iCalendar protocols and data formats.
setup      : |
    %cmake -DSHARED_ONLY=yes -DLIB_SUFFIX=64 .
build      : |
    %make
install    : |
    %make_install
