name       : libical
version    : 3.0.9
release    : 10
source     :
    - https://github.com/libical/libical/releases/download/v3.0.9/libical-3.0.9.tar.gz : bd26d98b7fcb2eb0cd5461747bbb02024ebe38e293ca53a7dfdcb2505265a728
license    : MPL-2.0
component  : desktop.library
summary    : An implementation of the iCalendar protocols and data formats
description: |
    Libical is an Open Source implementation of the iCalendar protocols and protocol data units. The iCalendar specification describes how calendar clients can communicate with calendar servers so users can store their calendar data and arrange meetings with other users.
builddeps  :
    - db5-devel
    - vala
rundeps    :
    - devel :
        - db5-devel
setup      : |
    %cmake_ninja -DICAL_GLIB_VAPI=yes \
        -DGOBJECT_INTROSPECTION=yes \
        -DENABLE_GTK_DOC=no \
        -DLIB_SUFFIX=64 \
        -DSHARED_ONLY=yes
build      : |
    %ninja_build
install    : |
    %ninja_install
